src/components/app-main.js
=> closing and navigating cellphone sidebar

jest.config.json, package.json, test/jest-pretest.js, test/react-unit/app-main.spec.js, test/react-unit/buymusic.spec.js, test/react-unit/fof.spec.js, test/react-unit/index.spec.js, test/react-unit/music.spec.js, test/react-unit/picSlider.spec.js, test/react-unit/tour-table.spec.js
#35 
@JoshuaVSherman this is branched-off the `test branch`, so I suggest you merge this into the test branch first.
=> Jest setup

src/components/app-main.js
=> code-climate issue fixes

src/App/Home.js, src/App/Homepage/Narrowscreen/NarrowAbout.js, src/App/Homepage/Narrowscreen/NarrowCurrentProjects.js, src/App/Homepage/OHAF.js, src/App/Homepage/Widescreen/WideAbout.js, src/App/Homepage/Widescreen/WideCurrentProjects.js, test/react-unit/App/home.spec.js
=> WIP fixes homepage

src/components/MusicPlayer/index.js
Reverts WebJamApps/JaMmusic#250
=> Revert "Shuffle button and code climate"

package.json, src/components/MusicPlayer/index.js
=> shufflefix

package.json, src/components/MusicPlayer/index.js
Reverts WebJamApps/JaMmusic#258
=> Revert "shufflefix"

.gitignore, src/containers/MusicDashboard/index.js, src/lib/forms.js
@JoshuaVSherman from what I've read from the documentation and over on stackoverflow, this may fix it ?
I don't have access to the MusicDashboard to test it, but from both the error and what I read:
One of the input fields is changing our state variables. They're all set to a default when the component first renders, and are being changed through setState, but then it changes when it hits the backend (if I'm reading that error correctly, anyways.)
If it's not the values themselves that are messing things up, my other guess is that it has to do with the createTourAPI, given it's the only piece that looks like it's changing not based directly on user input.
=> Controlled components fix

test/App/songActions.spec.tsx
Not sure if <any> typing is best suited for the dispatch, but I'm not sure what would be better suited here.
=> Fixes testing to remove ts-ignore

src/containers/Music/wjBand.tsx
Small update to fix problem with children in wjBand's table.
=> Update to fix console warning

test/components/DashNavigationButtons/index.spec.tsx, test/components/TourEditor/index.spec.tsx
I am not sure which branch this is appropriate to push to. So I will just add them with additional tests for song editor
=> Additional testing dash nav buttons

src/components/DashNavigationButtons/index.tsx
=> refactor dash nav

src/components/DashNavigationButtons/index.tsx, static/_mobile.scss, static/_music.scss
=> fix dash nav for other devices

src/components/DashNavigationButtons/index.tsx, static/_mobile.scss, static/_music.scss, static/styles.scss
#606 
I still need to adjust width of dash bar to stop before scroll bar
=> buttons dont wrap

src/components/DashNavigationButtons/index.tsx, static/_mobile.scss, static/_music.scss
=> cover header for all screen sizes

static/_mobile.scss, static/_music.scss
=> Music dash nav refactor

src/components/TourTable/DataTable.tsx, test/components/TourTable.spec.tsx
=> Issue 630 test sort

static/_slideshow.scss, test/containers/MusicDashboard/MusicDashboardController.spec.tsx
=> fix to show caption

static/_mobile.scss
[Still doesn't support Galaxy Fold fully. Will fix that when I refactor  SASS.]
=> Fixes layout issues on mobile

src/App/AppTemplate/SideMenuItem.tsx, test/App/AppTemplate/SideMenuItem.spec.tsx, test/App/AppTemplate/__snapshots__/index.spec.tsx.snap
Reverts WebJamApps/JaMmusic#832
=> Revert "Fix login"
